# Generated by Django 5.2.5 on 2025-08-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
