# Generated by Django 5.2.5 on 2025-08-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='model',
            field=models.CharField(default='lustify-sdxl', max_length=100),
        ),
    ]
