# Generated by Django 5.2.5 on 2025-08-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='masks',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
