# Generated by Django 5.2.5 on 2025-09-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_masks'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='scale',
            field=models.IntegerField(default=4),
        ),
    ]
