# Generated by Django 5.2.5 on 2025-09-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='finish_model',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='guidance_scale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='passes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='seed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='steps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='strength',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='upscale_model',
            field=models.CharField(default='realesrgan-x4plus'),
        ),
    ]
