# Generated by Django 5.2.5 on 2025-09-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_finish_model_job_guidance_scale_job_passes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inputs/'),
        ),
    ]
