# Generated by Django 5.2.5 on 2025-09-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='negative_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
