# Generated by Django 5.2.5 on 2025-09-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_job_negative_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='upscale_model',
            field=models.CharField(blank=True, null=True),
        ),
    ]
