# Generated by Django 5.2.5 on 2025-09-04 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_job_user_alter_job_session_id_jobevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='scale',
        ),
    ]
