# Generated by Django 5.2.5 on 2025-09-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_remove_job_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobevent',
            name='payload',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
