# Generated by Django 5.2.5 on 2025-09-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_jobevent_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobevent',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
